export const supportedLanguages = [
  { code: "en", label: "🇺🇸 English" },
  { code: "fr", label: "🇫🇷 Français" },
  { code: "de", label: "🇩🇪 Deutsch" },
  { code: "es", label: "🇪🇸 Español" },
  { code: "it", label: "🇮🇹 Italiano" },
  { code: "pt", label: "🇵🇹 Português" },
  { code: "nl", label: "🇳🇱 Nederlands" },
  { code: "sv", label: "🇸🇪 Svenska" },
  { code: "da", label: "🇩🇰 Dansk" },
  { code: "no", label: "🇳🇴 Norsk" },
  { code: "fi", label: "🇫🇮 Suomi" },
  { code: "pl", label: "🇵🇱 Polski" },
  { code: "ar", label: "🇸🇦 العربية" },
  { code: "zh", label: "🇨🇳 中文" },
  { code: "ja", label: "🇯🇵 日本語" },
  { code: "ko", label: "🇰🇷 한국어" },
  { code: "th", label: "🇹🇭 ไทย" },
  { code: "uk", label: "🇺🇦 Українська" },
  { code: "vi", label: "🇻🇳 Tiếng Việt" },
  { code: "ms", label: "🇲🇾 Bahasa Melayu" },
  { code: "ro", label: "🇷🇴 Română" },
  { code: "ru", label: "🇷🇺 Русский" },
];